version: '3.7'

services:
  terraform:
    image: hashicorp/terraform:0.12.21
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - access_key = ${ACCESS_KEY}
      - secret_key = ${SECRET_KEY}
      - region = ${AWS_REGION}

